### PR TITLE
fix crypt causing segfault

### LINKED ISSUE #26: Doesn't lock
I reinstalled `sflock` today, building it from sources in Arch through the AUR package. `sflock` doesn't lock, it starts, but accepts any string as the correct password.

### PR DESCRIPTION
**Pull request by ghost**
fixes #26 and #24

### CODE REVIEW

**Comment by benruijl** [comment]
Very nice, thank you!

File: sflock.c [hunk 1]
```diff
@@ -110,7 +111,7 @@ main(int argc, char **argv) {
             }
             else
                 if (!strcmp(argv[i], "-v")) 
-                    die("sflock-"VERSION", © 2015 Ben Ruijl\n");
+                    die("sflock-\"VERSION\", © 2015 Ben Ruijl\n");
```
Comment (benruijl) [inline sflock.c]: This is actually correct. The version variable is set in the makefile.

**Review by benruijl — CHANGES_REQUESTED** [review]
